---
- name: Install dependencies for rbenv
  become: yes
  become_user: "{{ rbenv.user }}"
  apt: pkg=git
  tags: rbenv

- name: Install rbenv
  become: yes
  become_user: "{{ rbenv.user }}"
  git: repo=https://github.com/rbenv/rbenv.git dest=~/.rbenv version={{ rbenv.version }}
  tags: rbenv

- name: Add ~.rbenv/bin to PATH
  become: yes
  become_user: "{{ rbenv.user }}"
  lineinfile: >
    dest="~/.profile"
    line="export PATH=$HOME/.rbenv/bin:$PATH"
  tags: rbenv

- name: Eval rbenv init in ~/.profile
  become: yes
  become_user: "{{ rbenv.user }}"
  lineinfile: >
    dest="~/.profile"
    line='eval "$(rbenv init -)"'
  tags: rbenv

- name: Copy .gemrc to ~/.gemrc
  become: yes
  become_user: "{{ rbenv.user }}"
  copy: src={{ item }} dest=~/.gemrc
  with_first_found:
    - ../../../files/.gemrc
    - .gemrc
  tags: rbenv

- name: Install dependencies for ruby-build
  become: yes
  become_user: root
  apt: pkg={{ item }}
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6
    - libreadline6-dev
    - zlib1g
    - zlib1g-dev
    - libffi-dev
    - ruby-all-dev
  tags: rbenv

- name: Install ruby-build as rbenv plugin
  become: yes
  become_user: "{{ rbenv.user }}"
  git: repo=https://github.com/rbenv/ruby-build.git dest=~/.rbenv/plugins/ruby-build
  tags: rbenv

- name: Check if {{ rbenv.ruby_version }} is installed
  shell: "sudo -iu {{ rbenv.user }} rbenv versions | grep {{ rbenv.ruby_version }}"
  register: rbenv_check_install
  changed_when: False
  ignore_errors: True
  tags: rbenv

- name: Clear previous shims
  file: state=absent path=~/.rbenv/shims/.rbenv-shim 
  tags: rbenv

- name: "Install {{ rbenv.ruby_version }}"
  command: "sudo -iu {{ rbenv.user }} rbenv install {{ rbenv.ruby_version }}"
  when: rbenv_check_install|failed
  tags: rbenv

- name: "Check if {{ rbenv.ruby_version }} is the default ruby version"
  shell: "sudo -iu {{ rbenv.user }} rbenv version | grep {{ rbenv.ruby_version }}"
  register: rbenv_check_default
  changed_when: False
  ignore_errors: True
  tags: rbenv

- name: "Set default ruby version to {{ rbenv.ruby_version }}"
  command: "sudo -iu {{ rbenv.user }} rbenv global {{ rbenv.ruby_version }}"
  when: rbenv_check_default|failed
  tags: rbenv

- name: "Install bundler to {{ rbenv.ruby_version }}"
  become: yes
  become_user: "{{ rbenv.user }}"
  shell: "rbenv local {{ rbenv.ruby_version }} && gem install bundler"
  tags: rbenv

# - name: "Update rbenv from master"
#   become: yes
#   become_user: "{{ rbenv.user }}"
#   command: "cd ~/.rbenv && git pull"
#   tags: rbenv
